### PR TITLE
commit tree c3c70b47c2aad50e7fd12b0345c6d268817e566e

### PR DESCRIPTION
**Pull request by Ludcad615**

### CODE REVIEW

**Comment by lizbur10** [comment]
Hi there,

It looks like this pull request was submitted as proof of your completion of
this lab/assignment. This pull request will not submit your work correctly so
I am closing it.

Please [review these instructions](https://github.com/learn-co-curriculum/welcome-completing-assignments) on completing and submitting your work.


If you continue to have difficulties, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in
Canvas to connect with a Technical Coach on the Academic Success Team.

Thanks! 💙

**Comment by Ludcad615** [comment]
[Ludwig_Cadet_Resume.docx](https://github.com/learn-co-curriculum/phase-4-active-record-associations-review-lab/files/9123579/Ludwig_Cadet_Resume.docx)

**Comment by Ludcad615** [comment]
Did you not receive it ?

**Comment by Ludcad615** [comment]
Can you try it again?

**Comment by lizbur10** [comment]
Hi! I see you attached your resume above - if you need to submit your resume somewhere, this isn't the right place. 😄

**Comment by Ludcad615** [comment]
Hey Liz,

I'm sorry I was in panic mode because I noticed that my google link was
private.

Regards,

Ludwig Cadet

**Pull request closed without merging**
